# Generated by Django 3.2 on 2022-09-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220909_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'meysamn', 'verbose_name_plural': 'mysamsssss'},
        ),
    ]
