# Generated by Django 3.2 on 2022-09-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'meysamn', 'verbose_name_plural': 'mey=samssssss'},
        ),
    ]
